import * as fs from 'fs';
import * as path from 'path';
import { createTransactionWrapper } from '../src/consensus/types';
import { bytesToHex } from '../src/internal/bytes';

/**
 * Round-trips the SDK's single transaction encoder against golden wire JSON
 * produced (and verified to deserialize) by the real Rust
 * `willow_types::Transaction` enum — the exact type the API server's
 * `Json<Transaction>` extractor parses.
 *
 * The golden in tests/fixtures/tx-wire/wrappers.json was generated by
 * tests/fixtures/tx-wire/src/main.rs, which serializes each tx with serde_json
 * and asserts `serde_json::from_str::<Transaction>` accepts it. So a match here
 * proves the SDK emits a shape the chain deserializes — catching any regression
 * to hex-string signatures/digests or camelCase keys mechanically.
 *
 * The fixed inputs below mirror the Rust generator's constants exactly.
 */

const GOLDEN = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'fixtures', 'tx-wire', 'wrappers.json'), 'utf8'),
).wrappers as Record<string, Record<string, unknown>>;

const SUBGROVE_ID = 'private-data';
const OWNER_DID = 'did:willow:owner';
const KEY_ID = 'did:willow:owner#key-1';
const FILE_KEY = 'file-1';
const NODE_DID = 'did:willow:storage1';
const NONCE = 7;

/** 64-byte ed25519 signature: bytes 0..64, as the hex the SDK is handed. */
const SIGNATURE_HEX = bytesToHex(Uint8Array.from(Array.from({ length: 64 }, (_, i) => i)));

/** 32-byte digest hex matching the Rust generator's `digest(seed)`. */
function digestHex(seed: number): string {
  return bytesToHex(Uint8Array.from(Array.from({ length: 32 }, (_, i) => (seed + i) & 0xff)));
}

const GRANT = {
  grantee_did: 'did:willow:reader',
  key_epoch: 1,
  grantee_public_key_id: 'did:willow:reader#key-1',
  ephemeral_public_key: [1, 2, 3],
  encrypted_key: [4, 5, 6],
  granted_by: OWNER_DID,
  granted_at: 1_700_000_000,
};

/**
 * Compare a wrapper to its golden. The Rust serializer emits `Option::None`
 * fields as explicit `null` (e.g. StoreFileManifest.encryption); the SDK omits
 * them, which serde accepts via `#[serde(default)]`. Drop golden keys whose
 * value is `null` before comparing so we test the bytes the SDK actually
 * sends, not serde's None representation.
 */
function goldenWithoutNulls(variant: string): Record<string, unknown> {
  const inner = GOLDEN[variant][variant] as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(inner)) {
    if (v !== null) out[k] = v;
  }
  return { [variant]: out };
}

describe('createTransactionWrapper — round-trip against the real Rust Transaction', () => {
  it('StoreFileManifest matches the golden wire shape (byte-array digests + signature)', () => {
    const wrapper = createTransactionWrapper('StoreFileManifest', {
      subgroveId: SUBGROVE_ID,
      fileKey: FILE_KEY,
      filename: 'doc.json',
      contentType: 'application/json',
      totalSize: 17,
      contentHash: digestHex(0x11),
      chunkCount: 1,
      chunkSize: 262_144,
      chunkMerkleRoot: digestHex(0x22),
      ownerDid: OWNER_DID,
      signature: SIGNATURE_HEX,
      publicKeyId: KEY_ID,
      nonce: NONCE,
    });
    expect(wrapper).toEqual(goldenWithoutNulls('StoreFileManifest'));
  });

  it('DeleteFileManifest matches the golden wire shape', () => {
    const wrapper = createTransactionWrapper('DeleteFileManifest', {
      subgroveId: SUBGROVE_ID,
      fileKey: FILE_KEY,
      ownerDid: OWNER_DID,
      signature: SIGNATURE_HEX,
      publicKeyId: KEY_ID,
      nonce: NONCE,
    });
    expect(wrapper).toEqual(goldenWithoutNulls('DeleteFileManifest'));
  });

  it('UnregisterStorageNode matches the golden wire shape', () => {
    const wrapper = createTransactionWrapper('UnregisterStorageNode', {
      nodeDid: NODE_DID,
      signature: SIGNATURE_HEX,
      publicKeyId: KEY_ID,
      nonce: NONCE,
    });
    expect(wrapper).toEqual(goldenWithoutNulls('UnregisterStorageNode'));
  });

  it('GrantSubgroveKey matches the golden wire shape (embedded grant byte fields)', () => {
    const wrapper = createTransactionWrapper('GrantSubgroveKey', {
      subgroveId: SUBGROVE_ID,
      encryptedKeyGrant: GRANT,
      senderDid: OWNER_DID,
      signature: SIGNATURE_HEX,
      publicKeyId: KEY_ID,
      nonce: NONCE,
    });
    expect(wrapper).toEqual(goldenWithoutNulls('GrantSubgroveKey'));
  });

  it('RevokeSubgroveKey matches the golden wire shape', () => {
    const wrapper = createTransactionWrapper('RevokeSubgroveKey', {
      subgroveId: SUBGROVE_ID,
      revokeeDid: 'did:willow:reader',
      senderDid: OWNER_DID,
      signature: SIGNATURE_HEX,
      publicKeyId: KEY_ID,
      nonce: NONCE,
    });
    expect(wrapper).toEqual(goldenWithoutNulls('RevokeSubgroveKey'));
  });

  it('RotateSubgroveKey matches the golden wire shape', () => {
    const wrapper = createTransactionWrapper('RotateSubgroveKey', {
      subgroveId: SUBGROVE_ID,
      newEpoch: 2,
      newGrants: [GRANT],
      senderDid: OWNER_DID,
      signature: SIGNATURE_HEX,
      publicKeyId: KEY_ID,
      nonce: NONCE,
    });
    expect(wrapper).toEqual(goldenWithoutNulls('RotateSubgroveKey'));
  });

  it('throws on an unknown tx type instead of emitting a camelCase passthrough', () => {
    expect(() =>
      createTransactionWrapper('NotARealTx', { foo: 'bar' } as never),
    ).toThrow(/Unknown transaction type/);
  });
});
